### ISSUE TITLE
Error: LinkageError occurred while loading main class io.simplelocalize.cli.SimplelocalizeCliCommand

### ISSUE THREAD

**Issue by capaj** [simplelocalize/github-action-cli#3]
Trying to run it, I am getting:
```
Run simplelocalize/github-action-cli@v3
Run actions/setup-java@v4
Installed distributions
Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Run echo "command: upload"
command: upload
cli-version: 2.6.0
args: 
Run curl -o simplelocalize.jar https://get.simplelocalize.io/binaries/2.6.0/simplelocalize-cli-2.6.0.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6747k  100 6747k    0     0  64[55](https://github.com/XXX/YYYY/actions/runs/10920891718/job/30311762615#step:7:59)k      0  0:00:01  0:00:01 --:--:-- 6462k
Run java -jar simplelocalize.jar upload --apiKey *** 
Error: LinkageError occurred while loading main class io.simplelocalize.cli.SimplelocalizeCliCommand
	java.lang.UnsupportedClassVersionError: io/simplelocalize/cli/SimplelocalizeCliCommand has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to [64](https://github.com/talentpilot/ts-monorepo/actions/runs/10920891718/job/30311762615#step:7:69).0
```

**Comment by philjones88** [comment]
I hit this too, ended up pulling out the contents of the GHA and doing like:

```
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "Download SimpleLocalize CLI"
        run: "curl -o simplelocalize.jar https://get.simplelocalize.io/binaries/${{ env.SIMPLELOCALIZE_CLI_VERSION }}/simplelocalize-cli-${{ env.SIMPLELOCALIZE_CLI_VERSION }}.jar"
        shell: bash

     - name: Upload translations
        shell: bash
        run: "java -jar simplelocalize.jar upload --apiKey ${{ secrets.SIMPLELOCALIZE_API_KEY }} --uploadPath ${{ inputs.path}}{lang}/{ns}.json --uploadFormat single-language-json --uploadOptions REPLACE_TRANSLATION_IF_FOUND,DELETE_NOT_PRESENT_KEYS"
```
